[package]
name = "oxidize"
version = "0.1.0"
edition = "2021"

[dependencies]
bump2version = "0.1.3"
chrono = "0.4.38"
thiserror = "2.0.3"
hdwallet = "0.4.1"
sha2 = "0.10.8"
bip39 = { version = "2.1.0", features = ["rand"] }
colored = "2.1.0"
tokio = "1.41.1"
