// Consts
pub const BLOCKCHAIN_INITIAL_DIFFICULTY: u8 = 2;
pub const BLOCKCHAIN_INITIAL_NONCE: u64 = 0;
pub const BLOCKCHAIN_OXCOIN_SUPPLY: u64 = 1_000_000;
pub const BLOCKCHAIN_COINBASE_FEE: u64 = 20;
pub const BLOCKCHAIN_TRANSACTION_FEE: u8 = 1;